// Copyright (c) 2021 Xu Shaohua <shaohua@biofan.org>. All rights reserved.
// Use of this source is governed by GNU Lesser General Public License
// that can be found in the LICENSE file.

#ifndef RUSTY_RUSTY_BASE_CRASH_REPORTER_H_
#define RUSTY_RUSTY_BASE_CRASH_REPORTER_H_

#include <QString>

namespace rusty {

struct CrashReporterPrivate;

// CrashReporter manages crash report files generated by breakpad.
class CrashReporter {
 public:
  CrashReporter();
  ~CrashReporter();

  void setDumpDir(const QString& path);
  const QString& dumpDir() const;

 private:
  CrashReporterPrivate* p_;
};

}  // namespace rusty

#endif  // RUSTY_RUSTY_BASE_CRASH_REPORTER_H_
